name: pill_reminder
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.6
  get_storage: ^2.1.1
  http: ^1.2.1
  intl: ^0.19.0
  logger: ^2.2.0
  url_launcher: ^6.2.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  # - - - - - -  LOCAL ASSETS - - - - - - #
  assets:
    - assets/animations/
  
  # - - - - - -  LOCAL FONTS - - - - - - #
  fonts:
    - family: bold
      fonts:
        - asset: assets/fonts/bold.ttf
    
    - family: med
      fonts:
        - asset: assets/fonts/med.ttf

    - family: light
      fonts:
        - asset: assets/fonts/light.ttf
